CREATE TABLE ‘MONITORAMENTO‘
(
‘ID‘ int(11) NOT NULL AUTO_INCREMENT,
‘TIMESTAMP‘ timestamp NOT NULL DEFAULT
CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
‘TEMPERATURA‘ double NOT NULL,
‘UMIDADE‘ double NOT NULL,
PRIMARY KEY (‘ID‘)
)